### ISSUE TITLE
Does not compile with HASS 2024.3.1

### ISSUE THREAD

**Issue by krangchen** [m5stack/M5CoreS3-Esphome#9]
Hey,

The compile fails after I upgraded HASS from 2024.2.1 to 2024.3.1 (or 2024.3.3) with the following error:

Compiling .pioenvs\m5core3-wz-66aa74\lib611\M5GFX\lgfx\v1\panel\Panel_HasBuffer.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:677:56: error: invalid new-expression of abstract class type 'esphome::m5cores3_display::M5CoreS3Display'
   m5cores3_lcd = new m5cores3_display::M5CoreS3Display();
                                                        ^
In file included from src/esphome.h:30,
                 from src/main.cpp:3:
src/esphome\components\m5cores3_display\m5cores3_display.h:7:7: note:   because the following virtual functions are pure within 'esphome::m5cores3_display::M5CoreS3Display':
 class M5CoreS3Display : public display::Display {
       ^~~~~~~~~~~~~~~
In file included from src/esphome.h:18,
                 from src/main.cpp:3:
src/esphome\components\display\display.h:636:15: note:  'virtual int esphome::display::Display::get_height_internal()'
   virtual int get_height_internal() = 0;
               ^~~~~~~~~~~~~~~~~~~
src/esphome\components\display\display.h:637:15: note:  'virtual int esphome::display::Display::get_width_internal()'
   virtual int get_width_internal() = 0;
               ^~~~~~~~~~~~~~~~~~
*** [.pioenvs\m5core3-wz-66aa74\src\main.cpp.o] Error 1

Anybody to fix?

**Comment by lboue** [comment]
@krangchen 
Did you try to post a message on [M5Stack Discord](https://discord.gg/2T7ZE2j)?

**Comment by lboue** [comment]
Same issue for me:


```
Dependency Graph
|-- AsyncTCP-esphome @ 2.1.3
|-- M5GFX @ 0.1.14
|-- M5Unified @ 0.1.13
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
```

[logs_cores3-voice-assistant_compile.txt](https://github.com/m5stack/M5CoreS3-Esphome/files/14816945/logs_cores3-voice-assistant_compile.txt)

**Comment by krangchen** [comment]
> @krangchen Did you try to post a message on [M5Stack Discord](https://discord.gg/2T7ZE2j)?

Can do, seems like I can soon start collecting Discord Server to hang out with.
But if that's easier to get the developers/maintainers attention, I'd rather do that. Thanks for the link, though :)

**Comment by rleinfellner** [comment]
So near & yet so far, same issue here. Any ideas welcome

**Comment by krangchen** [comment]
HASS 2024.4.x with ESPHome 2024.3.2 also not working...

**Comment by rleinfellner** [comment]
Has repo this been abandoned? If so time to move on maybe?

**Comment by krangchen** [comment]
Looks like, still no success in compiling
In received the Espressif version, way better support there. Luckily I ordered one each and can now make a decision on e.g. support where to spent my money on ;)

**Comment by Forairaaaaa** [comment]
Hi, i'll check

**Comment by gunnm80** [comment]
Thank you @vample. It works for me. At least implement the YAML. Must now test whether the voice control also works.

**Comment by labricolenumerique** [comment]
> I know this probably isn't the correct way to fix the problem, but I was able to get the yaml to compile an run by changing the display section to this:
> 
> `spi: clk_pin: GPIO36 mosi_pin: GPIO37
> 
> display:
> 
> * platform: ili9xxx
>   id: m5cores3_lcd
>   model: M5Stack
>   dimensions: 320x240
>   cs_pin: GPIO3
>   dc_pin: GPIO35
>   update_interval: never`

@vampler Could you edit your message to show the YAML code with source code formatting? It would be easier to read.

**Comment by lboue** [comment]
Here's what it looks like:

```
spi :
  clk_pin : GPIO36
  mosi_pin: GPIO37

display :
  - platform: ili9xxx
# - platform : m5cores3_display
    model : ILI9342
    dc_pin : 35
    update_interval : never
    id : m5cores3_lcd
spi:
  clk_pin: GPIO36
  mosi_pin: GPIO37

display:
  - platform: ili9xxx
# - platform: m5cores3_display
    model: ILI9342
    dc_pin: 35
    update_interval: never
    id: m5cores3_lcd
```

**Comment by lboue** [comment]
Fixed by my PR #12.

**Comment by BillyFKidney** [comment]
> Fixed by my PR #12. You can try by replacing the `external_components `section by this one:
> 
> ```yaml
> external_components:
>   - source:
>       type: git
>       url: https://github.com/lboue/M5CoreS3-Esphome
>       ref: m5cores3_display
>     components: [ board_m5cores3, m5cores3_audio, m5cores3_display ]
> ```

This resolved the display issue, but the sound crackles horribly.
Is this expected?

**Comment by gunnm80** [comment]
> > Fixed by my PR #12. You can try by replacing the `external_components `section by this one:
> > ```yaml
> > external_components:
> >   - source:
> >       type: git
> >       url: https://github.com/lboue/M5CoreS3-Esphome
> >       ref: m5cores3_display
> >     components: [ board_m5cores3, m5cores3_audio, m5cores3_display ]
> > ```
> 
> This resolved the display issue, but the sound crackles horribly. Is this expected?

Yes, unfortunately. See also [](https://github.com/m5stack/M5CoreS3-Esphome/issues/8.) I'm experimenting a bit. But it would be great if the developers could get to work. I believe that this device is far better than the ESP32-S3-BOX-3, if only because of the voice output.

**Comment by lboue** [comment]
@
> Yes, unfortunately. See also ##8. I'm experimenting a bit. But it would be great if the developers could get to work. I believe that this device is far better than the ESP32-S3-BOX-3, if only because of the voice output.

That's not the subject of this thread. Please don't mix things up

**Comment by BillyFKidney** [comment]
> > Yes, unfortunately. See also ##8. I'm experimenting a bit. But it would be great if the developers could get to work. I believe that this device is far better than the ESP32-S3-BOX-3, if only because of the voice output.
> 
> @gunnm80 That's not the subject of this thread. Please don't mix things up.
> 
> @krangchen Can you close this thread?

I asked because I replaced _board_m5cores3, m5cores3_audio, m5cores3_display_ instead of just _m5cores3_display_

I will look at the other thread for the audio issues.

**Comment by lboue** [comment]
@krangchen Can you close this issue?
